New Monitr
toolsforexperiments/plottr pull request #354
Opened 2022-12-05 15:29 UTC by pfafflabatuiuc

A new version of Monitr with more features. For a guide on how to use see: https://toolsforexperiments-manual.readthedocs.io/en/latest/plottr/apps.html#monitr

2022-12-05 17:58 UTC, pfafflabatuiuc commented
I have added watchdog as a testing requirement in test_requirements.txt. Should I add it as a requirement in requirements.txt and the setup file?

2022-12-05 23:17 UTC, wpfff requested changes
this works well, but please fix typos in filenames (and elsewhere if there are any ;)) and add watchdog to the requirements.

2022-12-05 23:17 UTC, wpfff commented on plottr/apps/json_veiwer.py
> +"""
fix typo in filename

2022-12-06 02:35 UTC, wpfff approved these changes
looks good now.

2022-12-06 02:36 UTC, merged